//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace aspnetmvc2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP
    {
        public string ID { get; set; }
        public string NAME { get; set; }
        public string SEX { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string DEPT_CD { get; set; }
    }
}
